import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '相谈甚多',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梦爱吃鱼',
				sitenick: '',
				title: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: getFavicon('blog.bsgun.cn'),
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: [],
				date: '2025-08-17',
				comment: '',
			}, {
				author: '纸鹿本鹿',
				sitenick: '',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: getFavicon('blog.zhilu.site'),
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: [],
				date: '2025-08-17',
				comment: '',
			}, {
				author: 'Mo的记事簿',
				sitenick: '',
				title: 'Mo的记事簿',
				desc: '万年鸽王，哈哈OvO',
				link: 'https://blog.xiowo.net/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: getFavicon('blog.xiowo.net'),
				avatar: 'https://blog.xiowo.net/img/avatar.png',
				archs: [],
				date: '2025-08-18',
				comment: '',
			}, {
				author: '清羽飞扬',
				sitenick: '',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: getFavicon('blog.liushen.fun'),
				avatar: 'https://blog.liushen.fun/info/avatar.ico',
				archs: [],
				date: '2025-08-18',
				comment: '',
			}, {
				author: '间窗',
				sitenick: '',
				title: '间窗的博客',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.jcblog.com.cn',
				feed: 'https://www.jcblog.com.cn/feed.xml',
				icon: getFavicon('jcblog.com.cn'),
				avatar: getGhAvatar('DohhhDo'),
				archs: [],
				date: '2025-08-22',
				comment: '',
			}, {
				author: '尘',
				sitenick: '',
				title: '尘の个人博客',
				desc: '一个高中生 UP 搭的博客 QwQ',
				link: 'https://blog.mcxiaochen.top/',
				feed: '',
				icon: getFavicon('blog.mcxiaochen.top'),
				avatar: 'https://blog.mcxiaochen.top/favicon.ico',
				archs: [],
				date: '2025-08-22',
				comment: '',
			}, {
				author: 'H2O',
				sitenick: '',
				title: 'THW’s Blog',
				desc: 'Live a good life meet slowly',
				link: 'https://thw.lol',
				feed: '',
				icon: getFavicon('thw.lol'),
				avatar: 'https://thw.lol/wp-content/uploads/2025/07/1753346514-DM_20250723205301_001.jpg',
				archs: [],
				date: '2025-08-24',
				comment: '',
			},
		],
	},
] satisfies FeedGroup[]